### PR TITLE
feat(labels): add branch to label regex

### PR DESCRIPTION
**Pull request by bbbmj**
**What this PR does / why we need it**:

- add `/branch` to label regex

**Special notes for your reviewer**:

/cc @ddysher @ijumps
@HarrisChu do you have any requirement about the labels?

### CODE REVIEW

**Comment by deyuanix** [comment]
I think @HarrisChu requires `/queue` and `/version`

**Comment by bbbmj** [comment]
`/queue` and `/version` have added

**Comment by bbbmj** [comment]
@ddysher updated. PTAl

**Review by deyuanix — APPROVED** [review]

**Comment by deyuanix** [comment]
@bbbmj can you also update bot image?

**Comment by bbbmj** [comment]
@ddysher the bot image was updated and tested

**Pull request merged**
