### PR TITLE
Revert "Add LgtmActsAsApprove option to approve plugin"

### PR DESCRIPTION
**Pull request by bbbmj**
This reverts commit 3cf183aecd1fb2c79e64fe5a6ed216ef4ab9eafa.

/release-note-none
/cc @ddysher @supereagle

### CODE REVIEW

**Comment by deyuanix** [comment]
why do you revert the commit instead of using bool option?

**Comment by bbbmj** [comment]
> why do you revert the commit instead of using bool option?

if we use it, we need to specify repo names like:

```
approve:
- repos:
  - kubernetes/charts
  - kubernetes/kube-deploy
  - kubernetes/kubectl
  - kubernetes/kubernetes
  - kubernetes/kubernetes-template-project
  - kubernetes/kube-state-metrics
  - kubernetes/minikube
  - kubernetes/test-infra
  implicit_self_approve: true
  lgtm_acts_as_approve: true
```

**Comment by bbbmj** [comment]
what we really want is the default value is `true`

**Comment by deyuanix** [comment]
what's the problem with this?  because se want to use org hooks?
> if we use it, we need to specify repo names like:

**Comment by bbbmj** [comment]
> 如果有人想要 lgtm acts as approve ，可以私聊我。

我原本在 slack 里说的，是想着保持  lgtm acts as approve 默认是 false，如果有需求私聊我单独加。

但是，我们想要的是默认值是 true，两种改法：
1. revert
2. 修改代码逻辑

**Comment by deyuanix** [comment]
LGTM

it's easier for us to use 'lgtm acts as approve' since we have fewer devs per repo

**Pull request merged**
